# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-30 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
