# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-02 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170502_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
